// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDK_WNv_fvp8zcVLlCTHzV0G8s3yAQHY',
    appId: '1:75396238674:web:f07ed80d0073bfe420fe8b',
    messagingSenderId: '75396238674',
    projectId: 'livelifeapplicaton',
    authDomain: 'livelifeapplicaton.firebaseapp.com',
    storageBucket: 'livelifeapplicaton.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRh4ifSygzbv8aW3MfasQlN5c1RCjxgPE',
    appId: '1:75396238674:android:bb8fa119c9ba427920fe8b',
    messagingSenderId: '75396238674',
    projectId: 'livelifeapplicaton',
    storageBucket: 'livelifeapplicaton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbWk0scqc-SJfebZbJJcbY_Y8Nj4lazw',
    appId: '1:75396238674:ios:629b53b9f9f2ce9320fe8b',
    messagingSenderId: '75396238674',
    projectId: 'livelifeapplicaton',
    storageBucket: 'livelifeapplicaton.appspot.com',
    iosBundleId: 'com.example.livelife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbWk0scqc-SJfebZbJJcbY_Y8Nj4lazw',
    appId: '1:75396238674:ios:629b53b9f9f2ce9320fe8b',
    messagingSenderId: '75396238674',
    projectId: 'livelifeapplicaton',
    storageBucket: 'livelifeapplicaton.appspot.com',
    iosBundleId: 'com.example.livelife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDK_WNv_fvp8zcVLlCTHzV0G8s3yAQHY',
    appId: '1:75396238674:web:5c31c3fc6c13f15620fe8b',
    messagingSenderId: '75396238674',
    projectId: 'livelifeapplicaton',
    authDomain: 'livelifeapplicaton.firebaseapp.com',
    storageBucket: 'livelifeapplicaton.appspot.com',
  );
}
